@LegalManager_HostAddress = http://localhost:5133

GET {{LegalManager_HostAddress}}/api/users/
Accept: application/json

###

GET {{LegalManager_HostAddress}}/api/cases/
Accept: application/json

###

GET {{LegalManager_HostAddress}}/api/appointments/
Accept: application/json

###

GET {{LegalManager_HostAddress}}/api/appointments/availability?lawyerId=1&date=2026-09-15
Accept: application/json